/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.3.72"

    // Apply the application plugin to add support for building a CLI application.
    application
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
    mavenCentral()
    // google() // biasanya untuk android
}

dependencies {
    // implementation, adalah dependency yang digunakan oleh kode program kita
    // testImplementation, adalah dependency yang digunakan oleh  kode unit test kita

    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")

    // Add coroutine
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.7")

    implementation("com.google.code.gson:gson:2.8.6")

    // add subprojects
    implementation(project(":belajar-gradle-model"))
    implementation(project(":belajar-gradle-util"))
}

application {
    // Define the main class for the application.
    mainClassName = "gradle.AppKt"
}

tasks.register("helloworld") {
    doFirst {
        println("Hello")
    }
    doLast {
        println("World!")
    }
}

tasks.register("author") {
    val author: String by project
    val email: String by project
    doFirst {
        println("Author name: $author")
    }
    doLast {
        println("Author email: $email")
    }
}
